### ISSUE TITLE
gfxmonk.net certificate error

### ISSUE THREAD

**Issue by jayvdb** [timbertson/termstyle#10]
https://gfxmonk.net/dist/0install/python-termstyle.xml (https) shows a certificate error  SSL_ERROR_BAD_CERT_DOMAIN. The certificate is only valid for the following names: *.nfshost.com, nfshost.com

**Comment by timbertson** [comment]
The site isn't set up for https, it's not generally needed for 0install since all archives are GPG signed.

**Comment by timbertson** [comment]
It's also on pypi if that bothers you: https://pypi.org/project/termstyle/

**Comment by jayvdb** [comment]
G'day @timbertson , the reason I was reporting this was because it causes a problem with my new tool, which tries to use https where possible. See https://github.com/jayvdb/pypidb/search?q=gfxmonk.net&unscoped_q=gfxmonk.net where I have had to add a explicit workaround.  This is a problem with https://pypi.org/project/python-termstyle/ , not https://pypi.org/project/termstyle .  I could introduce new mechanisms to deal with this, especially mapping of old names for packages which have been renamed, but that is a bit off.

**Comment by timbertson** [comment]
Ah, fair enough. Can your tool just mark the package as broken in cases like this? Since `termstyle` is the newer one it seems not that bad if people can't access the older python-termstyle in your tool :man_shrugging:

**Comment by jayvdb** [comment]
I want to avoid having lots of per-project specific rules.  The existing low level "https exception" is a better approach, and I plan to move a lot of those rules into HTTPS Everywhere rules (c.f. https://github.com/jayvdb/https-everywhere-py)

But it is still useful to be able to link old project names to new names, so I have created an issue for that.
